### ISSUE TITLE
文字の演算が出来ない

### ISSUE THREAD

**Issue by buyoh** [buyoh/nospace#1]
次のコードがコンパイルエラー

```
__putc('0' + 1);
```

**Comment by thaliaarchi** [comment]
I think that this issue has already been fixed. When I compile and run that example, it works:

```sh
$ echo -n "func:main(){__putc('0'+1);}" > test.ns
$ maicomp < test.ns > test.ws
$ ruby vm/run.rb test.ws test/empty.txt
1
```

**Comment by buyoh** [comment]
Thank you for reports! It's interesting...
I confirmed now that it works in many cases, but the code with spaces doesn't work.
The operation with characters has no problem, but there are bugs in the syntactic analysis.
```
func:main(){
  # __putc('0' + 1);  # compile error!
  __putc('0'+1);
  __putc(('0') + 1);

  __putc(48 + 1);
  __putc(48+1);
  __putc((48) + 1);
}
```

**Comment by buyoh** [comment]
The root causes of the problem was very simple so I've committed and close this issue.
Thank you for your contributes!
