### ISSUE TITLE
Line comments are whitespace-sensitive

### ISSUE THREAD

**Issue by thaliaarchi** [buyoh/nospace#6]
Line comments in Nospace are ended with LF or CR, so if all whitespace characters are removed from a program, everything after the comment is now commented out. This kind of defeats the purpose of Nospace, that is, whitespace can be removed and the program will still run. I propose replacing `#` line comments with `#-` `-#` block comments. If you like this idea, I could submit a PR for this.

**Comment by thaliaarchi** [comment]
I also considered `/*` `*/` like C, `(*` `*)` like Pascal, and `{-` `-}` like Haskell, but `/` `(` `{` are already used, so parsing would be a little more complicated.

**Comment by buyoh** [comment]
I think that simple `# block comments #` is enough. It's similar to python’s triple quotes.
The compatibility will be lost, but it looks not good for comments to depend white-spaces.

**Comment by buyoh** [comment]
Thank you! I merged to 73d7276
